; Auto-generated. Do not edit!


(cl:in-package inv_kinematics-msg)


;//! \htmlinclude footend_pos.msg.html

(cl:defclass <footend_pos> (roslisp-msg-protocol:ros-message)
  ((footend_FL
    :reader footend_FL
    :initarg :footend_FL
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (footend_FR
    :reader footend_FR
    :initarg :footend_FR
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (footend_BL
    :reader footend_BL
    :initarg :footend_BL
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (footend_BR
    :reader footend_BR
    :initarg :footend_BR
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass footend_pos (<footend_pos>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <footend_pos>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'footend_pos)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name inv_kinematics-msg:<footend_pos> is deprecated: use inv_kinematics-msg:footend_pos instead.")))

(cl:ensure-generic-function 'footend_FL-val :lambda-list '(m))
(cl:defmethod footend_FL-val ((m <footend_pos>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inv_kinematics-msg:footend_FL-val is deprecated.  Use inv_kinematics-msg:footend_FL instead.")
  (footend_FL m))

(cl:ensure-generic-function 'footend_FR-val :lambda-list '(m))
(cl:defmethod footend_FR-val ((m <footend_pos>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inv_kinematics-msg:footend_FR-val is deprecated.  Use inv_kinematics-msg:footend_FR instead.")
  (footend_FR m))

(cl:ensure-generic-function 'footend_BL-val :lambda-list '(m))
(cl:defmethod footend_BL-val ((m <footend_pos>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inv_kinematics-msg:footend_BL-val is deprecated.  Use inv_kinematics-msg:footend_BL instead.")
  (footend_BL m))

(cl:ensure-generic-function 'footend_BR-val :lambda-list '(m))
(cl:defmethod footend_BR-val ((m <footend_pos>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inv_kinematics-msg:footend_BR-val is deprecated.  Use inv_kinematics-msg:footend_BR instead.")
  (footend_BR m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <footend_pos>) ostream)
  "Serializes a message object of type '<footend_pos>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'footend_FL))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'footend_FL))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'footend_FR))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'footend_FR))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'footend_BL))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'footend_BL))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'footend_BR))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'footend_BR))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <footend_pos>) istream)
  "Deserializes a message object of type '<footend_pos>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'footend_FL) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'footend_FL)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'footend_FR) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'footend_FR)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'footend_BL) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'footend_BL)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'footend_BR) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'footend_BR)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<footend_pos>)))
  "Returns string type for a message object of type '<footend_pos>"
  "inv_kinematics/footend_pos")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'footend_pos)))
  "Returns string type for a message object of type 'footend_pos"
  "inv_kinematics/footend_pos")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<footend_pos>)))
  "Returns md5sum for a message object of type '<footend_pos>"
  "9e96999e07cf2518ba50b0eeed74e99c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'footend_pos)))
  "Returns md5sum for a message object of type 'footend_pos"
  "9e96999e07cf2518ba50b0eeed74e99c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<footend_pos>)))
  "Returns full string definition for message of type '<footend_pos>"
  (cl:format cl:nil "# 四足机器狗的落脚点坐标，各数组长度为3~%float32[] footend_FL  # 左前腿~%float32[] footend_FR  # 右前腿~%float32[] footend_BL  # 左后腿~%float32[] footend_BR  # 右后腿~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'footend_pos)))
  "Returns full string definition for message of type 'footend_pos"
  (cl:format cl:nil "# 四足机器狗的落脚点坐标，各数组长度为3~%float32[] footend_FL  # 左前腿~%float32[] footend_FR  # 右前腿~%float32[] footend_BL  # 左后腿~%float32[] footend_BR  # 右后腿~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <footend_pos>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'footend_FL) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'footend_FR) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'footend_BL) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'footend_BR) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <footend_pos>))
  "Converts a ROS message object to a list"
  (cl:list 'footend_pos
    (cl:cons ':footend_FL (footend_FL msg))
    (cl:cons ':footend_FR (footend_FR msg))
    (cl:cons ':footend_BL (footend_BL msg))
    (cl:cons ':footend_BR (footend_BR msg))
))
