; Auto-generated. Do not edit!


(cl:in-package inv_kinematics-msg)


;//! \htmlinclude servo_pos.msg.html

(cl:defclass <servo_pos> (roslisp-msg-protocol:ros-message)
  ((servo_FL
    :reader servo_FL
    :initarg :servo_FL
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (servo_FR
    :reader servo_FR
    :initarg :servo_FR
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (servo_BL
    :reader servo_BL
    :initarg :servo_BL
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (servo_BR
    :reader servo_BR
    :initarg :servo_BR
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass servo_pos (<servo_pos>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <servo_pos>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'servo_pos)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name inv_kinematics-msg:<servo_pos> is deprecated: use inv_kinematics-msg:servo_pos instead.")))

(cl:ensure-generic-function 'servo_FL-val :lambda-list '(m))
(cl:defmethod servo_FL-val ((m <servo_pos>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inv_kinematics-msg:servo_FL-val is deprecated.  Use inv_kinematics-msg:servo_FL instead.")
  (servo_FL m))

(cl:ensure-generic-function 'servo_FR-val :lambda-list '(m))
(cl:defmethod servo_FR-val ((m <servo_pos>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inv_kinematics-msg:servo_FR-val is deprecated.  Use inv_kinematics-msg:servo_FR instead.")
  (servo_FR m))

(cl:ensure-generic-function 'servo_BL-val :lambda-list '(m))
(cl:defmethod servo_BL-val ((m <servo_pos>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inv_kinematics-msg:servo_BL-val is deprecated.  Use inv_kinematics-msg:servo_BL instead.")
  (servo_BL m))

(cl:ensure-generic-function 'servo_BR-val :lambda-list '(m))
(cl:defmethod servo_BR-val ((m <servo_pos>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader inv_kinematics-msg:servo_BR-val is deprecated.  Use inv_kinematics-msg:servo_BR instead.")
  (servo_BR m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <servo_pos>) ostream)
  "Serializes a message object of type '<servo_pos>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'servo_FL))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'servo_FL))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'servo_FR))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'servo_FR))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'servo_BL))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'servo_BL))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'servo_BR))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'servo_BR))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <servo_pos>) istream)
  "Deserializes a message object of type '<servo_pos>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'servo_FL) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'servo_FL)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'servo_FR) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'servo_FR)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'servo_BL) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'servo_BL)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'servo_BR) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'servo_BR)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<servo_pos>)))
  "Returns string type for a message object of type '<servo_pos>"
  "inv_kinematics/servo_pos")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'servo_pos)))
  "Returns string type for a message object of type 'servo_pos"
  "inv_kinematics/servo_pos")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<servo_pos>)))
  "Returns md5sum for a message object of type '<servo_pos>"
  "227a6f2238ca813c514b004a793abc3a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'servo_pos)))
  "Returns md5sum for a message object of type 'servo_pos"
  "227a6f2238ca813c514b004a793abc3a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<servo_pos>)))
  "Returns full string definition for message of type '<servo_pos>"
  (cl:format cl:nil "# 四足机器狗的舵机目标角度，各数组长度为3~%float32[] servo_FL  # 左前腿~%float32[] servo_FR  # 右前腿~%float32[] servo_BL  # 左后腿~%float32[] servo_BR  # 右后腿~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'servo_pos)))
  "Returns full string definition for message of type 'servo_pos"
  (cl:format cl:nil "# 四足机器狗的舵机目标角度，各数组长度为3~%float32[] servo_FL  # 左前腿~%float32[] servo_FR  # 右前腿~%float32[] servo_BL  # 左后腿~%float32[] servo_BR  # 右后腿~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <servo_pos>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'servo_FL) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'servo_FR) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'servo_BL) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'servo_BR) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <servo_pos>))
  "Converts a ROS message object to a list"
  (cl:list 'servo_pos
    (cl:cons ':servo_FL (servo_FL msg))
    (cl:cons ':servo_FR (servo_FR msg))
    (cl:cons ':servo_BL (servo_BL msg))
    (cl:cons ':servo_BR (servo_BR msg))
))
