# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from inv_kinematics/servo_pos.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class servo_pos(genpy.Message):
  _md5sum = "9869e38db82380d0fa3c5aff4375b3b3"
  _type = "inv_kinematics/servo_pos"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 legID
float64 rollAng
float64 pitchAng1
float64 pitchAng2"""
  __slots__ = ['legID','rollAng','pitchAng1','pitchAng2']
  _slot_types = ['int64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       legID,rollAng,pitchAng1,pitchAng2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(servo_pos, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.legID is None:
        self.legID = 0
      if self.rollAng is None:
        self.rollAng = 0.
      if self.pitchAng1 is None:
        self.pitchAng1 = 0.
      if self.pitchAng2 is None:
        self.pitchAng2 = 0.
    else:
      self.legID = 0
      self.rollAng = 0.
      self.pitchAng1 = 0.
      self.pitchAng2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q3d().pack(_x.legID, _x.rollAng, _x.pitchAng1, _x.pitchAng2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.legID, _x.rollAng, _x.pitchAng1, _x.pitchAng2,) = _get_struct_q3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q3d().pack(_x.legID, _x.rollAng, _x.pitchAng1, _x.pitchAng2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.legID, _x.rollAng, _x.pitchAng1, _x.pitchAng2,) = _get_struct_q3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q3d = None
def _get_struct_q3d():
    global _struct_q3d
    if _struct_q3d is None:
        _struct_q3d = struct.Struct("<q3d")
    return _struct_q3d
