// Generated by gencpp from file penu/LenCmd.msg
// DO NOT EDIT!


#ifndef PENU_MESSAGE_LENCMD_H
#define PENU_MESSAGE_LENCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace penu
{
template <class ContainerAllocator>
struct LenCmd_
{
  typedef LenCmd_<ContainerAllocator> Type;

  LenCmd_()
    : len_cmd1(0)
    , len_cmd2(0)
    , len_cmd3(0)
    , len_cmd4(0)  {
    }
  LenCmd_(const ContainerAllocator& _alloc)
    : len_cmd1(0)
    , len_cmd2(0)
    , len_cmd3(0)
    , len_cmd4(0)  {
  (void)_alloc;
    }



   typedef uint16_t _len_cmd1_type;
  _len_cmd1_type len_cmd1;

   typedef uint16_t _len_cmd2_type;
  _len_cmd2_type len_cmd2;

   typedef uint16_t _len_cmd3_type;
  _len_cmd3_type len_cmd3;

   typedef uint16_t _len_cmd4_type;
  _len_cmd4_type len_cmd4;





  typedef boost::shared_ptr< ::penu::LenCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::penu::LenCmd_<ContainerAllocator> const> ConstPtr;

}; // struct LenCmd_

typedef ::penu::LenCmd_<std::allocator<void> > LenCmd;

typedef boost::shared_ptr< ::penu::LenCmd > LenCmdPtr;
typedef boost::shared_ptr< ::penu::LenCmd const> LenCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::penu::LenCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::penu::LenCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::penu::LenCmd_<ContainerAllocator1> & lhs, const ::penu::LenCmd_<ContainerAllocator2> & rhs)
{
  return lhs.len_cmd1 == rhs.len_cmd1 &&
    lhs.len_cmd2 == rhs.len_cmd2 &&
    lhs.len_cmd3 == rhs.len_cmd3 &&
    lhs.len_cmd4 == rhs.len_cmd4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::penu::LenCmd_<ContainerAllocator1> & lhs, const ::penu::LenCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace penu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::penu::LenCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::penu::LenCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::penu::LenCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::penu::LenCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::penu::LenCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::penu::LenCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::penu::LenCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0df90e8fef6c46a006fc379e47a36ad2";
  }

  static const char* value(const ::penu::LenCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0df90e8fef6c46a0ULL;
  static const uint64_t static_value2 = 0x06fc379e47a36ad2ULL;
};

template<class ContainerAllocator>
struct DataType< ::penu::LenCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "penu/LenCmd";
  }

  static const char* value(const ::penu::LenCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::penu::LenCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# length control command\n"
"uint16 len_cmd1\n"
"uint16 len_cmd2\n"
"uint16 len_cmd3\n"
"uint16 len_cmd4\n"
;
  }

  static const char* value(const ::penu::LenCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::penu::LenCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.len_cmd1);
      stream.next(m.len_cmd2);
      stream.next(m.len_cmd3);
      stream.next(m.len_cmd4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LenCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::penu::LenCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::penu::LenCmd_<ContainerAllocator>& v)
  {
    s << indent << "len_cmd1: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.len_cmd1);
    s << indent << "len_cmd2: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.len_cmd2);
    s << indent << "len_cmd3: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.len_cmd3);
    s << indent << "len_cmd4: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.len_cmd4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PENU_MESSAGE_LENCMD_H
